name: firestorepackage
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ^3.3.4

dependencies:
  flutter:
    sdk: flutter
  # LOCAL
  extensions:
    path: ../extensions
  models:
    path: ../models
  # FIREBASE
  firebase_core: 3.13.0
  firebase_core_web: 2.22.0
  firebase_core_platform_interface: 5.4.0
  cloud_firestore: 5.6.7

dev_dependencies:
  lintingpackage:
      path: ../lintingpackage