name: firestorepackage
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ^3.3.4

dependencies:
  flutter:
    sdk: flutter
  # LOCAL
  extensions:
    path: ../extensions
  models:
    path: ../models
  # FIREBASE
  firebase_core: 3.7.0
  firebase_core_web: 2.18.1
  firebase_core_platform_interface: 5.3.0
  cloud_firestore: 5.4.5

dev_dependencies:
  lintingpackage:
      path: ../lintingpackage